<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Violeta Rivera y Benjamín Sepulveda">

<title>Análisis Descriptivo de la Autopercepción Social y la Satisfacción Democrática en Chile (ELSOC 2016)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Rivera-Sepulveda-Trabajo1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/popper.min.js"></script>
<script src="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/anchor.min.js"></script>
<link href="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Rivera-Sepulveda-Trabajo1_files/libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Rivera-Sepulveda-Trabajo1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Rivera-Sepulveda-Trabajo1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Rivera-Sepulveda-Trabajo1_files/libs/bootstrap/bootstrap-2546a5edb573abd25b53f29b13f71942.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>
  body {
    text-align: justify;
    text-justify: inter-word;
  }
</style>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis Descriptivo de la Autopercepción Social y la Satisfacción Democrática en Chile (ELSOC 2016)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Violeta Rivera y Benjamín Sepulveda </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>En el contexto chileno actual, marcado por transformaciones políticas, desigualdades persistentes y un creciente distanciamiento entre ciudadanía e instituciones, se vuelve relevante comprender cómo las personas se perciben a sí mismas dentro del entramado social. Esta percepción subjetiva de la posición social puede incidir en diversas dimensiones de la vida, incluyendo las actitudes hacia la democracia y su evaluación.</p>
<p>Desde la sociología, resulta clave estudiar estos fenómenos considerando no solo las estructuras objetivas (como ingreso o educación), sino también las representaciones que las personas construyen respecto a su lugar en la sociedad. El presente estudio busca explorar la relación entre la <strong>autoubicación social subjetiva</strong> y la <strong>satisfacción con la democracia</strong> en Chile.</p>
<p>Entendemos por autoubicación social la forma en que los/as individuos/as se posicionan en una escala de estatus social percibido, medida del 0 (posición más baja) al 10 (más alta). Por su parte, la satisfacción con la democracia remite a la valoración que la ciudadanía hace del funcionamiento del régimen democrático, considerado un indicador clave de legitimidad política.</p>
<p>La relevancia sociológica de este estudio radica en que diversas investigaciones han mostrado que la percepción subjetiva del estatus social influye en la forma en que las personas se relacionan con instituciones, política y bienestar general <span class="citation" data-cites="mansteadPsychologySocialClass2018 krausSocialClassSense2009">(<a href="#ref-mansteadPsychologySocialClass2018" role="doc-biblioref">Manstead 2018</a>; <a href="#ref-krausSocialClassSense2009" role="doc-biblioref">Kraus, Piff, and Keltner 2009</a>)</span>. En contextos de alta desigualdad como el chileno, esta percepción puede alejarse de indicadores objetivos, pero aún así tener efectos significativos sobre las actitudes cívicas.</p>
<p>Nuestra hipótesis plantea que: <strong>a medida que aumenta la autoubicación social subjetiva (es decir, las personas se sienten en una mejor posición), tiende a aumentar la satisfacción con la democracia</strong>. Esta relación puede explicarse por una mayor sensación de integración y reconocimiento social entre quienes se perciben en una mejor posición.</p>
<p>La fuente de datos utilizada es la Encuesta Longitudinal Social de Chile (ELSOC), Ola 1 del año 2016. Esta encuesta es representativa a nivel nacional y permite analizar actitudes y percepciones sociales de la población adulta en el país.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carga Librerías --------------------------------------------------------------</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,  </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               car,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               stargazer,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>               sjlabelled,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>               sjPlot,      </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>               confintr,    </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>               gginference,  </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>               rempsyc,     </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>               broom,       </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>               sjmisc,      </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>               dplyr,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>               knitr,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>               flextable)           </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notacion cientifica</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># para limpiar el entorno de trabajo</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Carga datos ------------------------------------------------------------------</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"input/ELSOC_Long.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="selección-de-variables-y-justificación-sociológica" class="level1">
<h1>Selección de variables y justificación sociológica</h1>
<p><strong>1. Autoubicación en la sociedad chilena (<code>autoubi_socie</code>)</strong><br>
Esta variable recoge la percepción subjetiva de estatus social en una escala del 0 al 10. Su inclusión es central, ya que permite captar cómo las personas evalúan su lugar en la estructura social, considerando factores no siempre capturados por indicadores objetivos (como el capital cultural o simbólico). En estudios previos, esta percepción ha mostrado ser predictiva de bienestar, confianza y actitudes políticas <span class="citation" data-cites="operarioSubjectiveSocialStatus2004 krausSocialClassSense2009">(<a href="#ref-operarioSubjectiveSocialStatus2004" role="doc-biblioref">Operario, Adler, and Williams 2004</a>; <a href="#ref-krausSocialClassSense2009" role="doc-biblioref">Kraus, Piff, and Keltner 2009</a>)</span>.</p>
<p><strong>2. Satisfacción con el funcionamiento de la democracia (<code>satis_demo</code>)</strong><br>
Se trata de una variable ordinal que refleja la evaluación de las personas sobre la democracia chilena. Esta medida es clave para evaluar el vínculo entre ciudadanía e instituciones, especialmente en un país donde los niveles de confianza política han sido históricamente bajos. La sociología política ha demostrado que la percepción de justicia y representación se relaciona estrechamente con el nivel de satisfacción democrática <span class="citation" data-cites="norrisDemocraticDeficitCritical2011">(<a href="#ref-norrisDemocraticDeficitCritical2011" role="doc-biblioref">Norris 2011</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Filtrar y seleccionar -------------------------------------------------------</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> elsoc_long_2016_2022 <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ola<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(d01_01,c01)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Remover NA's ----------------------------------------------------------------</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">999</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Reetiquetado de variables</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"satis_demo"</span><span class="ot">=</span>c01,          </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"autoubi_socie"</span><span class="ot">=</span>d01_01) </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>satis_demo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(data<span class="sc">$</span>satis_demo, <span class="at">label =</span> <span class="st">"Satisfacción con el funcionamiento de la democracia"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>autoubi_socie <span class="ot">&lt;-</span> <span class="fu">set_label</span>(data<span class="sc">$</span>autoubi_socie, <span class="at">label =</span> <span class="st">"Autoubicación en la sociedad chilena"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualización-de-resultados" class="level1">
<h1>Visualización de resultados</h1>
<p>A continuación, se presenta una tabla descriptiva que resume las principales medidas estadísticas para las variables de interés en este estudio: autoubicación social subjetiva y satisfacción con la democracia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(data,<span class="at">type=</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==========================================
Statistic       N   Mean  St. Dev. Min Max
------------------------------------------
autoubi_socie 2,790 4.352  1.555    0  10 
satis_demo    2,790 1.995  1.084    1   5 
------------------------------------------</code></pre>
</div>
</div>
<pre><code></code></pre>
<pre><code></code></pre>
</section>
<section id="gráficos" class="level1">
<h1>Gráficos</h1>
<p>Teniendo nuestra tabla descriptiva como punto de partida, realizaremos a continuación una serie de gráficos que nos permitirán visualizar la distribución de las variables de interés. Estas representaciones gráficas facilitarán la comprensión de los patrones presentes en los datos y apoyarán la interpretación de los resultados obtenidos.</p>
<p><strong>Gráfico 1: Distribución de la autoubicación social subjetiva</strong></p>
<p>A continuación, se muestra un gráfico que representa la distribución de la variable&nbsp;<em>autoubicación social subjetiva</em>. Este gráfico permite observar cómo se concentran las respuestas a lo largo de la escala de 0 a 10, identificando posibles asimetrías, acumulaciones o extremos en la percepción del estatus social.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> autoubi_socie)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#F4A7B9"</span>) <span class="sc">+</span>  <span class="co"># rosado pastel</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Autoubicación en la sociedad chilena"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ubicación social (0 = más bajo, 10 = más alto)"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frecuencia"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_family =</span> <span class="st">"sans"</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rivera-Sepulveda-Trabajo1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Grafico 2</p>
<p>El siguiente gráfico muestra la distribución de la variable&nbsp;<em>satisfacción con la democracia</em>. Dado que esta se mide en una escala de 1 a 5, el gráfico facilita identificar tendencias generales en la valoración que hace la ciudadanía del funcionamiento democrático en Chile.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> satis_demo)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#CBAACB"</span>) <span class="sc">+</span>  <span class="co"># lila pastel</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Satisfacción con la democracia"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Nivel de satisfacción"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frecuencia"</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_family =</span> <span class="st">"sans"</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">25</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rivera-Sepulveda-Trabajo1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretación-de-resultados" class="level1">
<h1>Interpretación de resultados</h1>
<p>Los resultados descriptivos muestran que la autoubicación social subjetiva presenta un promedio de&nbsp;<strong>4.35</strong>&nbsp;en una escala de 0 a 10, con una desviación estándar de&nbsp;<strong>1.56</strong>. Esto sugiere que, en promedio, las personas se perciben en una posición intermedia-baja dentro de la escala social, con cierta dispersión en las respuestas. El mínimo reportado fue&nbsp;<strong>0</strong>&nbsp;y el máximo&nbsp;<strong>10</strong>, lo que indica que se utilizaron todos los niveles posibles de la escala.</p>
<p>Por otro lado, la satisfacción con la democracia tiene un promedio de&nbsp;<strong>1.99</strong>&nbsp;en una escala de 1 a 5, con una desviación estándar de&nbsp;<strong>1.08</strong>. Este resultado indica un nivel de satisfacción relativamente bajo entre las personas encuestadas, con una dispersión moderada. Aunque el valor máximo observado fue&nbsp;<strong>5</strong>, el promedio cercano a&nbsp;<strong>2</strong>&nbsp;sugiere una tendencia general hacia la insatisfacción con el funcionamiento de la democracia en Chile al momento de la medición.</p>
<p>En conjunto, los datos muestran que tanto la percepción del estatus social como la satisfacción con la democracia tienden a ubicarse en niveles bajos, lo que podría estar reflejando tensiones sociales importantes y una desconexión entre ciudadanía e instituciones. Estos resultados dan pie a profundizar en el análisis de la relación entre ambas variables.</p>
</section>
<section id="sección-trabajo-2-revisar" class="level1">
<h1>Sección Trabajo 2 revisar</h1>
<section id="asociación-entre-posición-socioeconómica-y-satisfacción-democrática" class="level2">
<h2 class="anchored" data-anchor-id="asociación-entre-posición-socioeconómica-y-satisfacción-democrática">Asociación entre posición socioeconómica y satisfacción democrática</h2>
<p>En esta sección se construye una base de datos nueva a partir de la Ola 1 de la Encuesta Longitudinal Social de Chile (ELSOC 2016), con el objetivo de explorar la relación entre la posición socioeconómica de las personas y su percepción sobre el funcionamiento de la democracia en Chile.</p>
<p>Se seleccionan variables clave como el nivel educacional, los ingresos líquidos mensuales, la satisfacción con la democracia, la autoubicación social, la tendencia política y percepciones sobre justicia en el acceso a educación y salud. Estas variables son renombradas, etiquetadas y tratadas para eliminar valores perdidos, permitiendo un análisis más claro.</p>
<p>Además, se realiza una recodificación de los ingresos en 10 tramos ordenados para facilitar su análisis comparativo. Posteriormente, se desarrollarán:</p>
<ul>
<li>Tablas de correlación entre nivel educacional, ingresos y satisfacción democrática, con el fin de evaluar asociaciones entre posición social y legitimidad del sistema democrático.</li>
<li>Índices y escalas construidas a partir de variables actitudinales, como percepciones de justicia y autoubicación social, que permitirán representar dimensiones más complejas.</li>
<li>Análisis exploratorios complementarios que contribuyan a caracterizar los perfiles sociales y sus percepciones políticas.</li>
</ul>
<p>Esta preparación metodológica sienta las bases para los análisis sustantivos que siguen en las siguientes secciones del trabajo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Filtrar y seleccionar -------------------------------------------------------</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> elsoc_long_2016_2022 <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ola<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">sexo=</span>m0_sexo,<span class="at">edad=</span>m0_edad,<span class="at">nedu=</span>m01,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>         m14,c01,c15,d01_01,d02_02,d02_03)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Remover NA's ----------------------------------------------------------------</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">999</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Reetiquetado de variables</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"nivel_educacional"</span><span class="ot">=</span>nedu,  <span class="co">#Nivel educacional.</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"ing_liqui_mens"</span><span class="ot">=</span>m14,      <span class="co">#Ingresos liquidos mensuales.</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"satis_demo"</span><span class="ot">=</span>c01,          <span class="co">#Satisfacción con el funcionamiento de la democracia.</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"tend_poli"</span><span class="ot">=</span>c15,           <span class="co">#Tendencia política.</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"autoubi_socie"</span><span class="ot">=</span>d01_01,    <span class="co">#Autoubicacion en la sociedad chilena.</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"just_acc_educ"</span><span class="ot">=</span>d02_02,    <span class="co">#Justicia en el acceso a educación según ingresos.</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"just_acc_salud"</span><span class="ot">=</span>d02_03)   <span class="co">#Justicia en el acceso a salud según ingresos.</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>nivel_educacional <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>nivel_educacional,<span class="at">label =</span> <span class="st">"Nivel educacional"</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>ing_liqui_mens <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>ing_liqui_mens,<span class="at">label =</span> <span class="st">"Ingresos liquidos mensuales"</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>satis_demo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>satis_demo,<span class="at">label =</span> <span class="st">"Satisfacción con el funcionamiento de la democracia"</span>)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>tend_poli <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>tend_poli,<span class="at">label =</span> <span class="st">"Tendencia política"</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>autoubi_socie <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>autoubi_socie,<span class="at">label =</span> <span class="st">"Autoubicacion en la sociedad chilena"</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>just_acc_educ <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>just_acc_educ,<span class="at">label =</span> <span class="st">"Justicia en el acceso a educación según ingresos"</span>)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>just_acc_salud <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> data<span class="sc">$</span>just_acc_salud,<span class="at">label =</span> <span class="st">"Justicia en el acceso a salud según ingresos"</span>)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Recodificación en 10 grupos más detallados</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>ing_liqui_mens <span class="ot">&lt;-</span> <span class="fu">case_when</span>(</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">==</span> <span class="dv">1</span>              <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">==</span> <span class="dv">2</span>              <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">%in%</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>          <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">%in%</span> <span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>          <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">%in%</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">8</span>          <span class="sc">~</span> <span class="dv">5</span>,</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">%in%</span> <span class="dv">9</span><span class="sc">:</span><span class="dv">10</span>         <span class="sc">~</span> <span class="dv">6</span>,</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">==</span> <span class="dv">11</span>             <span class="sc">~</span> <span class="dv">7</span>,</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">==</span> <span class="dv">12</span>             <span class="sc">~</span> <span class="dv">8</span>,</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">%in%</span> <span class="dv">13</span><span class="sc">:</span><span class="dv">14</span>        <span class="sc">~</span> <span class="dv">9</span>,</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>  data<span class="sc">$</span>ing_liqui_mens <span class="sc">%in%</span> <span class="dv">15</span><span class="sc">:</span><span class="dv">16</span>        <span class="sc">~</span> <span class="dv">10</span>,</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(data,<span class="at">type=</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=============================================
Statistic          N   Mean  St. Dev. Min Max
---------------------------------------------
sexo              192 1.474   0.501    1   2 
edad              192 45.167  12.852  19  73 
nivel_educacional 192 5.958   2.161    1  10 
ing_liqui_mens    192 6.693   2.407    1  10 
satis_demo        192 1.828   1.011    1   5 
tend_poli         192 7.880   4.135    0  12 
autoubi_socie     192 4.443   1.561    0  10 
just_acc_educ     192 1.948   0.885    1   5 
just_acc_salud    192 2.000   0.976    1   5 
---------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="asociación-de-variables-tabla-de-correlaciones-revisar" class="level2">
<h2 class="anchored" data-anchor-id="asociación-de-variables-tabla-de-correlaciones-revisar">Asociación de variables: tabla de correlaciones revisar</h2>
<p>En esta sección se analiza la <strong>asociación entre las variables principales</strong> del estudio, con el objetivo de explorar <strong>relaciones estadísticas entre el nivel educacional, los ingresos líquidos mensuales y la satisfacción con la democracia</strong>. Estas variables permiten observar cómo la posición socioeconómica se vincula con las percepciones sobre el funcionamiento democrático en Chile.</p>
<p>Se utiliza el coeficiente de correlación de <strong>Pearson</strong>, adecuado para variables numéricas u ordinales tratadas como continuas. La tabla de correlaciones entrega información sobre la <strong>dirección y fuerza de la asociación</strong> entre cada par de variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar paquete necesario</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Hmisc'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:sjmisc':

    %nin%</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:dplyr':

    src, summarize</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar las variables relevantes para la correlación</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cor_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(nivel_educacional, ing_liqui_mens, satis_demo)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación con significancia (r y p)</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(cor_data))</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar coeficientes de correlación</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>cor_matrix<span class="sc">$</span>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  nivel_educacional ing_liqui_mens  satis_demo
nivel_educacional        1.00000000     0.51994311  0.05900551
ing_liqui_mens           0.51994311     1.00000000 -0.03686345
satis_demo               0.05900551    -0.03686345  1.00000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar matriz de p-valores (significancia estadística)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>cor_matrix<span class="sc">$</span>P</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       nivel_educacional         ing_liqui_mens satis_demo
nivel_educacional                     NA 0.00000000000001088019  0.4162329
ing_liqui_mens    0.00000000000001088019                     NA  0.6117114
satis_demo        0.41623294294324164611 0.61171139718068889835         NA</code></pre>
</div>
</div>
<section id="interpretación-de-la-tabla-de-correlación" class="level3">
<h3 class="anchored" data-anchor-id="interpretación-de-la-tabla-de-correlación">Interpretación de la tabla de correlación</h3>
<p>La siguiente tabla muestra los coeficientes de correlación de Pearson entre tres variables clave del estudio: el nivel educacional, los ingresos líquidos mensuales y la satisfacción con el funcionamiento de la democracia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear matriz con redondeo</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cor_table <span class="ot">&lt;-</span> <span class="fu">round</span>(cor_matrix<span class="sc">$</span>r, <span class="dv">2</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar con stargazer</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(cor_table, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">title =</span> <span class="st">"Tabla de correlación entre variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Tabla de correlación entre variables
=============================================================
                  nivel_educacional ing_liqui_mens satis_demo
-------------------------------------------------------------
nivel_educacional         1             0.520        0.060   
ing_liqui_mens          0.520             1          -0.040  
satis_demo              0.060           -0.040         1     
-------------------------------------------------------------</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>La correlación entre <strong>nivel educacional</strong> e <strong>ingresos líquidos mensuales</strong> es positiva y moderada (r = 0.52), y estadísticamente significativa (p &lt; 0.001). Esto indica que a mayor nivel educativo, las personas tienden a declarar mayores ingresos, lo cual es consistente con los hallazgos tradicionales de la estratificación social.</p>
<p>En cambio, la correlación entre <strong>nivel educacional</strong> y <strong>satisfacción con la democracia</strong> es débil (r = 0.06) y no significativa (p = 0.41), al igual que la relación entre <strong>ingresos líquidos mensuales</strong> y <strong>satisfacción con la democracia</strong> (r = -0.04; p = 0.61). Esto sugiere que, en esta muestra, la <strong>posición socioeconómica no está asociada de forma clara con la legitimidad del sistema democrático</strong>, al menos según esta medida de satisfacción.</p>
<p>Estos resultados podrían reflejar que la satisfacción con la democracia en Chile no depende solamente de factores estructurales como ingresos o educación, sino que podría estar influida por otras dimensiones, como la percepción de corrupción, el desencanto con las élites políticas o las experiencias de participación ciudadana.</p>
</blockquote>
</section>
</section>
<section id="índice-y-escala-de-percepciones-de-justicia-distributiva-revisar" class="level2">
<h2 class="anchored" data-anchor-id="índice-y-escala-de-percepciones-de-justicia-distributiva-revisar">Índice y escala de percepciones de justicia distributiva (revisar)</h2>
<section id="índice-de-percepciones-de-justicia-distributiva" class="level3">
<h3 class="anchored" data-anchor-id="índice-de-percepciones-de-justicia-distributiva">Índice de percepciones de justicia distributiva</h3>
<section id="justificación-teórica" class="level4">
<h4 class="anchored" data-anchor-id="justificación-teórica">Justificación teórica</h4>
<p>Se construyó un índice compuesto para representar una dimensión de percepciones de justicia social en el acceso a bienes públicos. Este índice se compone de dos ítems: la percepción sobre justicia en el acceso a la educación y en el acceso a la salud, ambos evaluados según nivel de ingresos. Esta decisión se basa en estudios como el Informe de Desarrollo Humano del PNUD (2021) y reportes de la OCDE (2018), que destacan la centralidad de estos sectores en la reproducción de la desigualdad en Chile.</p>
</section>
<section id="variables-utilizadas" class="level4">
<h4 class="anchored" data-anchor-id="variables-utilizadas">2. Variables utilizadas</h4>
<ul>
<li><code>just_acc_educ</code>: ¿Qué tan justo considera el acceso a la educación según ingresos?</li>
<li><code>just_acc_salud</code>: ¿Qué tan justo considera el acceso a la salud según ingresos?</li>
</ul>
<p>Ambas variables utilizan una escala de 1 (Muy injusto) a 5 (Muy justo).</p>
</section>
<section id="construcción-del-índice" class="level4">
<h4 class="anchored" data-anchor-id="construcción-del-índice">3. Construcción del índice</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construcción del índice de justicia distributiva como promedio simple</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">indice_justicia =</span> (just_acc_educ <span class="sc">+</span> just_acc_salud) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="análisis-descriptivo-del-índice" class="level4">
<h4 class="anchored" data-anchor-id="análisis-descriptivo-del-índice">4. Análisis descriptivo del índice</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticos descriptivos del índice</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>indice_justicia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.000   2.000   1.974   2.000   5.000 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma del índice de justicia distributiva</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>indice_justicia,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribución del índice de justicia distributiva"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Índice de justicia"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#A8D5BA"</span>, <span class="at">breaks =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rivera-Sepulveda-Trabajo1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>La distribución del índice muestra una concentración en los valores bajos, lo que indica que la mayoría de las personas perciben injusticia en el acceso a educación y salud según ingresos.</p>
</blockquote>
</section>
</section>
<section id="escala-percepciones-de-justicia-distributiva" class="level3">
<h3 class="anchored" data-anchor-id="escala-percepciones-de-justicia-distributiva">Escala: Percepciones de justicia distributiva</h3>
<section id="justificación-conceptual" class="level4">
<h4 class="anchored" data-anchor-id="justificación-conceptual">1. Justificación conceptual</h4>
<p>Se construyó una escala a partir de los mismos dos ítems utilizados en el índice: percepción de justicia en el acceso a la educación y a la salud, ambas según nivel de ingresos. Se considera que estos ítems reflejan una misma actitud subyacente sobre la justicia distributiva percibida.</p>
<p>Este enfoque es coherente con estudios como el Informe de Desarrollo Humano del PNUD (2021) y reportes de la OCDE (2018), que destacan cómo estas áreas concentran las mayores preocupaciones ciudadanas sobre desigualdad en Chile.</p>
</section>
<section id="evaluación-de-la-consistencia-interna" class="level4">
<h4 class="anchored" data-anchor-id="evaluación-de-la-consistencia-interna">2. Evaluación de la consistencia interna</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar librería</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:Hmisc':

    describe</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    logit</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selección de ítems para la escala</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>escala_justicia <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(just_acc_educ, just_acc_salud)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular alfa de Cronbach</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>resultado_alpha <span class="ot">&lt;-</span> <span class="fu">alpha</span>(escala_justicia)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver valor del alfa crudo</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>resultado_alpha<span class="sc">$</span>total<span class="sc">$</span>raw_alpha</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8637841</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>El valor obtenido fue <strong>0.86</strong>, lo que indica una alta consistencia interna entre los ítems.</p>
</blockquote>
</section>
<section id="construcción-de-la-escala" class="level4">
<h4 class="anchored" data-anchor-id="construcción-de-la-escala">3. Construcción de la escala</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construcción de la escala como promedio simple</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">escala_justicia =</span> (just_acc_educ <span class="sc">+</span> just_acc_salud) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="análisis-descriptivo-de-la-escala" class="level4">
<h4 class="anchored" data-anchor-id="análisis-descriptivo-de-la-escala">4. Análisis descriptivo de la escala</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticos descriptivos de la escala</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>escala_justicia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.000   2.000   1.974   2.000   5.000 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma de la escala de percepciones de justicia distributiva</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>escala_justicia,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Escala de percepciones de justicia distributiva"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Promedio de respuestas (1 = muy injusto, 5 = muy justo)"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#A8D5BA"</span>, <span class="at">breaks =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rivera-Sepulveda-Trabajo1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>La distribución de la escala también muestra una tendencia hacia valores bajos, lo que sugiere que las personas tienden a percibir como injusto el acceso a servicios básicos según nivel de ingresos.</p>
</blockquote>
</section>
</section>
</section>
</section>
<section id="section" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-krausSocialClassSense2009" class="csl-entry" role="listitem">
Kraus, Michael W., Paul K. Piff, and Dacher Keltner. 2009. <span>“Social Class, Sense of Control, and Social Explanation.”</span> <em>Journal of Personality and Social Psychology</em> 97 (6): 992–1004. <a href="https://doi.org/10.1037/a0016357">https://doi.org/10.1037/a0016357</a>.
</div>
<div id="ref-mansteadPsychologySocialClass2018" class="csl-entry" role="listitem">
Manstead, Antony S. R. 2018. <span>“The Psychology of Social Class: <span>How</span> Socioeconomic Status Impacts Thought, Feelings, and Behaviour.”</span> <em>British Journal of Social Psychology</em> 57 (2): 267–91. <a href="https://doi.org/10.1111/bjso.12251">https://doi.org/10.1111/bjso.12251</a>.
</div>
<div id="ref-norrisDemocraticDeficitCritical2011" class="csl-entry" role="listitem">
Norris, Pippa. 2011. <em>Democratic <span>Deficit</span>: <span>Critical Citizens Revisited</span></em>. 1st ed. Cambridge University Press. <a href="https://doi.org/10.1017/CBO9780511973383">https://doi.org/10.1017/CBO9780511973383</a>.
</div>
<div id="ref-operarioSubjectiveSocialStatus2004" class="csl-entry" role="listitem">
Operario, Don, Nancy E. Adler, and David R. Williams. 2004. <span>“Subjective Social Status: Reliability and Predictive Utility for Global Health.”</span> <em>Psychology &amp; Health</em> 19 (2): 237–46. <a href="https://doi.org/10.1080/08870440310001638098">https://doi.org/10.1080/08870440310001638098</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>